sudo: required
services:
  - docker

script:
  - docker build -t engelbrod/node . 
  - docker images engelbrod/node

before_deploy:
  - docker login -u engelbrod -p 7622129rr

deploy:
  provider: script
  script: docker push engelbrod/node
  on:
    branch: master

